name: shake
description: A flutter package to detect phone shakes. Adjustable G-force and reset periods.
version: 2.2.0
homepage: 'https://www.github.com/deven98/shake'
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  sensors_plus: ^1.4.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.8
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
